version: 2.1

orbs:
  bundle-install: toshimaru/bundle-install@0.3.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - bundle-install/bundle-install
      - run:
          name: Check Outputs
          command: cd ruby && bash check.sh

workflows:
  sample:
    jobs:
      - build
